FROM oven/bun:1.4.0-slim

WORKDIR /app

# Установка OpenSSL и сертификатов для работы Prisma runtime в Linux
RUN apt-get update && apt-get install -y --no-install-recommends openssl ca-certificates && rm -rf /var/lib/apt/lists/*

COPY package.json bun.lock* ./
COPY apps/server/package.json ./apps/server/

RUN bun install --ignore-scripts

COPY . .

WORKDIR /app/apps/server

RUN bun run prisma:generate

ARG V_SERVER="dev"
ENV APP_VERSION=$V_SERVER
ENV PORT=8080
ENV NODE_ENV=production

EXPOSE 8080

CMD ["bun", "run", "start"]
